### ISSUE TITLE
미지원 브라우저로 접근시 지도가 안그려짐

### ISSUE THREAD

**Issue by junglesub** [milideal/client#14]
미지원 브라우저 접근시 지도가 그려지지 않습니다.

미지원 브라우저라고 이용자에게 알리는 기능이 있어야 할 것 같습니다.

**Comment by o-bard-o** [comment]
혹시 테스트 시 어떤 브라우저를 사용하셨는지 궁금합니다.

**Comment by o-bard-o** [comment]
해당 문제가 브라우저 지원 문제인지, 스크립트 로딩 시간의 문제인지 정확히 알 필요가 있을 것 같습니다.
https://devtalk.kakao.com/t/api/121883/3
만약 후자라면 https://apis.map.kakao.com/web/documentation/#load_load 이 링크대로 설정하면 해결 할 수 있을 것 같습니다.

**Comment by o-bard-o** [comment]
@junglesub 후자의 문제도 리액트 환경에서 자주 일어나는 문제임을 카카오 개발자 포럼에서 볼 수 있었습니다.
따라서, 해당 문제와 관련 없이 아래 커밋으로 이 이슈는 닫고, 만약 같은 문제가 재발된다면 다시 이슈를 만드는 게 어떨까 싶습니다.

참고로 카카오맵 자체에서 미지원 브라우저를 제공하지 않고 있으며, 우리가 불러오는 api에서 브라우저가 지원하지 않을 기능은 보이지 않기 때문에, 정섭님께서 목격한 문제가 스크립트 로딩 시간과 관련된 문제일 가능성이 높아보입니다.

**Comment by junglesub** [comment]
> 혹시 테스트 시 어떤 브라우저를 사용하셨는지 궁금합니다.

싸지방에서 접속했던거라 버전을 따로 적어두진 못했습니다.. 다만, 오늘 다시 시도했을 때는 특별한 문제가 없었기 때문에 또 다시 오류가 발생하면 그때 수정하는걸로 하겠습니다.

**Comment by junglesub** [comment]
<html>
<body>


Chrome | 98.0.4758.102 (공식 빌드) (64비트) (cohort: Stable)
-- | --
개정 | 273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}
OS | Windows 10 Version 21H2 (Build 19044.1566)
JavaScript | V8 9.8.177.11
사용자 에이전트 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36


</body>
</html>

![image](https://github.com/milideal/client/assets/42944002/4f9ed415-f69b-4419-ba73-02fe92152a79)

#18 이후에도 작동이 안됩니다.

미지원 브라우저라든지 로딩화면을 보여주는것이 좋을 것 같습니다. 혹시라도 사용자가 사용할 때 이렇게만 나오면 미완성되었다는 오해가 생길 것 같습니다.

최신 버전으로 업데이트 하고 나서는 잘 작동됩니다.
